import {SymbolSearch} from '../types/search/symbolSearch.types';

export const SYMBOLS = [
  {
    '1. symbol': 'I01.FRK',
    '2. name': 'IsoEnergy Ltd',
    '3. type': 'Equity',
    '4. region': 'Frankfurt',
    '5. marketOpen': '08:00',
    '6. marketClose': '20:00',
    '7. timezone': 'UTC+01',
    '8. currency': 'EUR',
    '9. matchScore': '0.3333',
  },
  {
    '1. symbol': 'I10.FRK',
    '2. name': 'Italgas S.p.A',
    '3. type': 'Equity',
    '4. region': 'Frankfurt',
    '5. marketOpen': '08:00',
    '6. marketClose': '20:00',
    '7. timezone': 'UTC+01',
    '8. currency': 'EUR',
    '9. matchScore': '0.3333',
  },
  {
    '1. symbol': 'I1M.FRK',
    '2. name': 'Indutrade AB (publ)',
    '3. type': 'Equity',
    '4. region': 'Frankfurt',
    '5. marketOpen': '08:00',
    '6. marketClose': '20:00',
    '7. timezone': 'UTC+01',
    '8. currency': 'EUR',
    '9. matchScore': '0.3333',
  },
  {
    '1. symbol': 'I25.FRK',
    '2. name': 'iRhythm Technologies Inc',
    '3. type': 'Equity',
    '4. region': 'Frankfurt',
    '5. marketOpen': '08:00',
    '6. marketClose': '20:00',
    '7. timezone': 'UTC+01',
    '8. currency': 'EUR',
    '9. matchScore': '0.3333',
  },
  {
    '1. symbol': 'I3B.FRK',
    '2. name': 'Independent Bank Group Inc',
    '3. type': 'Equity',
    '4. region': 'Frankfurt',
    '5. marketOpen': '08:00',
    '6. marketClose': '20:00',
    '7. timezone': 'UTC+01',
    '8. currency': 'EUR',
    '9. matchScore': '0.3333',
  },
  {
    '1. symbol': 'I3E.LON',
    '2. name': 'i3 Energy Plc',
    '3. type': 'Equity',
    '4. region': 'United Kingdom',
    '5. marketOpen': '08:00',
    '6. marketClose': '16:30',
    '7. timezone': 'UTC+00',
    '8. currency': 'GBX',
    '9. matchScore': '0.3333',
  },
  {
    '1. symbol': 'I3F.FRK',
    '2. name': 'Infinity Pharmaceuticals Inc',
    '3. type': 'Equity',
    '4. region': 'Frankfurt',
    '5. marketOpen': '08:00',
    '6. marketClose': '20:00',
    '7. timezone': 'UTC+01',
    '8. currency': 'EUR',
    '9. matchScore': '0.3333',
  },
  {
    '1. symbol': 'I2X2.FRK',
    '2. name': 'Intermediate Capital Group plc',
    '3. type': 'Equity',
    '4. region': 'Frankfurt',
    '5. marketOpen': '08:00',
    '6. marketClose': '20:00',
    '7. timezone': 'UTC+01',
    '8. currency': 'EUR',
    '9. matchScore': '0.2857',
  },
  {
    '1. symbol': 'I3A1.FRK',
    '2. name': 'Alien Metals Limited',
    '3. type': 'Equity',
    '4. region': 'Frankfurt',
    '5. marketOpen': '08:00',
    '6. marketClose': '20:00',
    '7. timezone': 'UTC+01',
    '8. currency': 'EUR',
    '9. matchScore': '0.2857',
  },
  {
    '1. symbol': 'I2PO.PAR',
    '2. name': 'IPPO SA',
    '3. type': 'Equity',
    '4. region': 'Paris',
    '5. marketOpen': '09:00',
    '6. marketClose': '17:30',
    '7. timezone': 'UTC+01',
    '8. currency': 'EUR',
    '9. matchScore': '0.2500',
  },
] as unknown as SymbolSearch[];
